### ISSUE TITLE
Can't open project in Lazarus 2.2.4 with FPC 3.2.2

### ISSUE THREAD

**Issue by JoeJoeTV** [varianus/ovoplayer#12]
### Description

I tried opening the `ovoplayer.lpi` and `ovoplayer.lpr` files using a relatively fresh installation of Lazarus 2.2.4 and at start, i get an error about the package `TThemedSlider` referencing itself multiple times before I get another error about TThemedSlider requiring `umain.pas` and an Access Violation from Lazarus itself.

### System Information

```
- Lazarus version: 2.2.4
- FPC version: 3.2.2
- OS: Linux Mint 21.2 Cinnamon 64 bit
```

### Notes

I have some packages installed including the various packages to make the IDE docked, but I'm not sure if this is the cause of this issue.

**Comment by varianus** [comment]
TThemedSlider is a custom component I wrote to handle volume and current song position. It is contained in the package mcaselli.lpk, avalaible in the src\components directory.
You need to install this package in Lazarus to successfully open the project in the IDE.

**Comment by JoeJoeTV** [comment]
Hmm, I installed the package, but I still can't open the project because of a different error (some text is in german):

"Read Error:"
```
Stream=TfMainForm: Root=:TfMainForm
Komponentenklasse: TTreeView
Error reading tvCollection.ShowSeparators: Unknown property: "ShowSeparators"
Streamposition: 4096
```

Does Ovoplayer have any other requirements that I may not have fullfilled?

**Comment by varianus** [comment]
Sorry, in the first reply  I missed that you are using Lazarus 2.2.4.
As stated in the readme file, OvoPlayer is developed in Lazarus 3.

You could try to manually remove line 165 ( "  ShowSeparators = False") from file umain.lfm before opening the project, but i'm not sure this is the only new property introduced by Lazarus 3.

**Comment by JoeJoeTV** [comment]
Sorry to reply again, but the readme (at least in the master branch) states that OvoPlayer is developed in Lazarus **2.0** and Free pascal **3.0.4**:
![image](https://github.com/varianus/ovoplayer/assets/34209417/4a4479ae-96a3-4dae-a31e-33ce513d6be7)

That's why I was confused that it didn't work in 2.2.4. Is this an error in the readme?

**Comment by varianus** [comment]
You are right.
I've modified build requirements in my working copy readme, but never committed it...
