### ISSUE TITLE
Unknown property: "PPI"

### ISSUE THREAD

**Issue by KottV** [varianus/ovoplayer#2]
well, I've successfully built Ovoplayer, but it gives me error at startup:

> [FORMS.PP] ExceptionOccurred 
>   Sender=EReadError
>   Exception=Error reading DM.PPI: Unknown property: "PPI"
>   Stack trace:
>   $00000000004CFAF6
>   $00000000004CEDB9
>   $0000000000545FAD
>   $0000000000545161
>   $00000000004CBBF9
>   $0000000000448695
> 

I've tried binaries from ppa with same result. Recompiling with qt5 or qt4 didn't help either

my distro: openSUSE Tumbleweed

**Comment by varianus** [comment]
PPA build machines have lazarus 1.6.4, their binaries will not work until launchpad upgrade to lazarus 1.8. 
The startup error should not happen when ovoplayer is built with lazarus 1.8. Anyway I'll do some more testing about it.
