### ISSUE TITLE
Missing mcaselli dependency

### ISSUE THREAD

**Issue by luigino** [varianus/ovoplayer#3]
Trying to package ovoplayer 1.3 for openSUSE, buildlinux.sh fails to produce ovoplayer with the error:
```
Error: (lazbuild) Broken dependency: mcaselli
```

Using lazarus 1.8.0 and fpc 3.0.4

**Comment by varianus** [comment]
I've just commited a fix in the build scripts.

**Comment by luigino** [comment]
That did the trick, TYVM.
