### ISSUE TITLE
How do you even use libmpv on windows ?

### ISSUE THREAD

**Issue by Naomi010Sentzke** [varianus/ovoplayer#5]
The option is greyed out. How doth I tell it the location of mpv-1.dll ?

**Comment by varianus** [comment]
The application search for mpv-1.dll in the following order:

1) in the same directory of ovoplayer.exe
2) in the windows\system32 directory (or windows\syswow64 if you are using a 64 bit Windows)
3) in directory specified as "Start in" in shortcut used to launch ovoplayer
4) in any directory specified by PATH environment variable
