### ISSUE TITLE
Animated png in mp3 tag?

### ISSUE THREAD

**Issue by fredvs** [varianus/ovoplayer#6]
Hello.

In the` test.mp3` in attachment was added a animated png.
https://en.wikipedia.org/wiki/APNG

Mostly all "classic" players can render the picture showing the first image of the animated png:

Here with VLC:

![Capture d’écran_2020-05-20_18-23-14](https://user-images.githubusercontent.com/3421249/82471454-028a2a00-9ac7-11ea-80c2-e1048daeb656.png)

But with `OvOplayer` the application crash, with message "invalid picture".

It would be great if OvOplayer could show the first picture of a animated PNG, and even better if it could render the animation (I did not find any player that does it).

Here the animated png included in the mp3:

![Animated_PNG](https://user-images.githubusercontent.com/3421249/82471824-89d79d80-9ac7-11ea-8022-bcc40b9bb131.png)

And here the mp3:

[test.mp3.tar.gz](https://github.com/varianus/ovoplayer/files/4658107/test.mp3.tar.gz)

Thanks.

Fre;D

PS: OvOplayer is very great and OvOtag is super WOW.

**Comment by varianus** [comment]
There was an error loading UTF-8 encoded image description, fixed with commit c9658b686fa0bf27269ca4dc64673e31c0dcd952
Thanks for bug report and appreciation.

**Comment by fredvs** [comment]
It works!

Thanks.
