### ISSUE TITLE
How to install uos?

### ISSUE THREAD

**Issue by fredvs** [varianus/ovoplayer#7]
Hello.
How to enable uos (United Openlib of Sound) engine?
Should the libraries be added into the system?

![Capture d’écran_2020-05-21_14-08-05](https://user-images.githubusercontent.com/3421249/82557992-0f615900-9b6d-11ea-8ad6-0092a10b385e.png)

**Comment by varianus** [comment]
To check for UOS availability I test result of uos_loadlib function:
```
...
CONST
{$IFDEF LINUX}
   PORTAUDIOLIB = 'system';
   SNDFILELIB   = 'system';
   MPG123LIB    = 'system';
   MP4FFLIB     = 'system';
   FAADLIB      = 'system';
   OPUSFILELIB  = 'system';
{$ENDIF LINUX}
{$IFDEF WINDOWS}
   PORTAUDIOLIB = 'libportaudio-32.dll';
   SNDFILELIB   = 'libsndfile-32.dll';
   MPG123LIB    = 'libmpg123-32.dll';
   MP4FFLIB     = 'LibMp4ff-32.dll';
   FAADLIB      = 'LibFaad2-32.dll';
   OPUSFILELIB  = 'LibOpusFile-32.dll';
{$ENDIF WINDOWS}    
   ...
  Result := uos_loadlib(PORTAUDIOLIB,
                       SNDFILELIB,
                       MPG123LIB,
                       MP4FFLIB,
                       FAADLIB,
                       OPUSFILELIB)=0; 

```
On Windows OS I initialize library name with the ones in your lib.zip releases, on Linux I prefer to use system installed library.

**Comment by fredvs** [comment]
Ha ok.

May I ask you how did you do to install 'libmp4ff.so.0.0.0' ?
I did try to find a debian package to install it without luck.

Maybe if you want to use the 'system' libraries of `uos`, you should disable to load the `MP4FFLIB` + `FAADLIB` because I fear there is no package for `MP4FFLIB` library (or maybe I miss something).
`FAADLIB` needs `MP4FFLIB` to work.


```
CONST
{$IFDEF LINUX}
   PORTAUDIOLIB = 'system';
   SNDFILELIB   = 'system';
   MPG123LIB    = 'system';
   MP4FFLIB     = '';
   FAADLIB      = '';
   OPUSFILELIB  = 'system';
{$ENDIF LINUX}
```
