### ISSUE TITLE
Libsndfile.pas - SF_COUNT_MAX

### ISSUE THREAD

**Issue by PeterOnDrums** [varianus/ovoplayer#8]
SF_COUNT_MAX = ctypes.clong($7FFFFFFFFFFFFFFF);
found in ovoplayer/src/import-engines/
as
- lazdyn_libsndfile.pas
- uos_libsndfile.pas

Instead type is ctypes.**clongclong**

prevents compiler warning ;-)

**Comment by fredvs** [comment]
Hello.

Here with fpc 3.2.0, `ctypes.clongclong` does not compile and gives the error:

> uos_libsndfile.pas(261,26) Error: Identifier not found "clongclong"

And I did not note a compiler warning for `ctypes.clong($7FFFFFFFFFFFFFFF)`

**Comment by fredvs** [comment]
Re-hello.

Ok, I get it, did change for `SF_COUNT_MAX = ctypes.clong($7FFFFFFFFFFFFFFF)` and compiler is happy now.

Committed your change for uos.
https://github.com/fredvs/uos/commit/97872212dcc72486afb856e5ef9eb382b7d4f842

Thanks to note it.

Fre;D
