### ISSUE TITLE
Genre numbers may exist in round brackets.

### ISSUE THREAD

**Issue by theo222** [varianus/ovoplayer#9]
https://www.lazarusforum.de/viewtopic.php?f=18&t=13493&p=120294#p120294
See HexEditor Screenshot.

Remove potential round brackets in unit Commonfunctions > function ExtractGenre > GenreString 

Thank you.

**Comment by varianus** [comment]
I didn't known this feature of genre tag.
Implemented in commit 73bc88b, close if ok

**Comment by theo222** [comment]
Thank you.
